<a href="https://colab.research.google.com/github/PriyankaMath/Tensor_Operations/blob/main/Tensors_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Basic Tensor Operations including einsum operations in Pytorch

**Submitted By:** Priyanka Math

## Importing Pytorch

In [ ]:
import torch
import numpy as np

## Initializing a Tensor

Tensors can be initialized in various ways.

#### Directly from data
Tensors can be created directly from data. The data type is automatically inferred.

In [ ]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


#### From a NumPy array
Tensors can be created from NumPy arrays (and vice versa - see Bridge with NumPy).

In [ ]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]])


#### From another tensor:
The new tensor retains the properties (shape, datatype) of the argument tensor, unless explicitly overridden.

In [ ]:
print(f"x_data Tensor: \n {x_data} \n")

x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

x_data Tensor: 
 tensor([[1, 2],
        [3, 4]]) 

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.9611, 0.5895],
        [0.8415, 0.1876]]) 



#### With random or constant values:
shape is a tuple of tensor dimensions. In the functions below, it determines the dimensionality of the output tensor.

In [ ]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.2532, 0.4660, 0.5442],
        [0.1635, 0.2193, 0.3387]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


## Attributes of a Tensor

Tensor attributes describe their shape, datatype, and the device on which they are stored.

In [ ]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape} \n")
print(f"Datatype of tensor: {tensor.dtype} \n")
print(f"Device tensor is stored on: {tensor.device} \n")

Shape of tensor: torch.Size([3, 4]) 

Datatype of tensor: torch.float32 

Device tensor is stored on: cpu 



## Operations on Tensors:

#### Standard numpy-like indexing and slicing:

In [ ]:
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]} \n")
print(f"First column: {tensor[:, 0]} \n")
print(f"Last column: {tensor[..., -1]} \n")
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.]) 

First column: tensor([1., 1., 1., 1.]) 

Last column: tensor([1., 1., 1., 1.]) 

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


#### Joining tensors
You can use torch.cat to concatenate a sequence of tensors along a given dimension.

In [ ]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


#### Arithmetic operations

Matrix Multiplication:

In [ ]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
tensor = torch.tensor([[1.0, 2.0],[3.0, 4.0]])
y1 = tensor @ tensor.T
print(f"y1: {y1} \n")

y2 = tensor.matmul(tensor.T)
print(f"y2: {y2} \n")

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)

y1: tensor([[ 5., 11.],
        [11., 25.]]) 

y2: tensor([[ 5., 11.],
        [11., 25.]]) 



tensor([[ 5., 11.],
        [11., 25.]])

Element-wise product:

In [ ]:
# This computes the element-wise product. z1, z2, z3 will have the same value
print(f"tensor: {tensor} \n")
z1 = tensor * tensor
print(f"z1: {z1} \n")
z2 = tensor.mul(tensor)
print(f"z2: {z2} \n")
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor: tensor([[1., 2.],
        [3., 4.]]) 

z1: tensor([[ 1.,  4.],
        [ 9., 16.]]) 

z2: tensor([[ 1.,  4.],
        [ 9., 16.]]) 



tensor([[ 1.,  4.],
        [ 9., 16.]])

Single-element tensors:

 If you have a one-element tensor, for example by aggregating all values of a tensor into one value, you can convert it to a Python numerical value using item():

In [ ]:
agg = tensor.sum()
print(agg, type(agg))
agg_item = agg.item()
print(agg_item, type(agg_item))

tensor(10.) <class 'torch.Tensor'>
10.0 <class 'float'>


In-place operations:

 Operations that store the result into the operand are called in-place. They are denoted by a _ suffix. For example: x.copy_(y), x.t_(), will change x.

In [ ]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[1., 2.],
        [3., 4.]]) 

tensor([[6., 7.],
        [8., 9.]])


## Einsum Operations

#### MATRIX TRANSPOSE

In [ ]:
a = torch.arange(6).reshape(2, 3) # Bji=Aij
print(f"a: {a} \n")
torch.einsum('ij->ji', [a])

a: tensor([[0, 1, 2],
        [3, 4, 5]]) 



tensor([[0, 3],
        [1, 4],
        [2, 5]])

#### SUM


In [ ]:
a = torch.arange(6).reshape(2, 3) # b= ∑i ∑j Aij = Aij
print(f"a: {a} \n")
torch.einsum('ij->', [a])

a: tensor([[0, 1, 2],
        [3, 4, 5]]) 



tensor(15)

#### COLUMN SUM

In [ ]:
a = torch.arange(6).reshape(2, 3) # bj = ∑i Aij = Aij
print(f"a: {a} \n")
torch.einsum('ij->j', [a])

a: tensor([[0, 1, 2],
        [3, 4, 5]]) 



tensor([3, 5, 7])

#### ROW SUM

In [ ]:
a = torch.arange(6).reshape(2, 3) # bi = ∑j Aij = Aij
print(f"a: {a} \n")
torch.einsum('ij->i', [a])

a: tensor([[0, 1, 2],
        [3, 4, 5]]) 



tensor([ 3, 12])

#### MATRIX-VECTOR MULTIPLICATION

In [ ]:
a = torch.arange(6).reshape(2, 3) # ci = ∑k Aik bk = Aikbk
print(f"a: {a} \n")
b = torch.arange(3)
print(f"b: {b} \n")
torch.einsum('ik,k->i', [a, b])

a: tensor([[0, 1, 2],
        [3, 4, 5]]) 

b: tensor([0, 1, 2]) 



tensor([ 5, 14])

#### MATRIX-MATRIX MULTIPLICATION

In [ ]:
a = torch.arange(6).reshape(2, 3) # Cij = ∑k Aik Bkj = Aik Bkj
print(f"a: {a} \n")
b = torch.arange(15).reshape(3, 5)
print(f"b: {b} \n")
torch.einsum('ik,kj->ij', [a, b])

a: tensor([[0, 1, 2],
        [3, 4, 5]]) 

b: tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]) 



tensor([[ 25,  28,  31,  34,  37],
        [ 70,  82,  94, 106, 118]])

#### DOT PRODUCT

In [ ]:
a = torch.arange(3)
print(f"a: {a} \n")
b = torch.arange(3,6)  # -- a vector of length 3 containing [3, 4, 5]
print(f"b: {b} \n")
torch.einsum('i,i->', [a, b])  # c = ∑i ai bi = aibi 

a: tensor([0, 1, 2]) 

b: tensor([3, 4, 5]) 



tensor(14)

#### Matrix:

In [ ]:
a = torch.arange(6).reshape(2, 3)
print(f"a: {a} \n")
b = torch.arange(6,12).reshape(2, 3)
print(f"b: {b} \n")
torch.einsum('ij,ij->', [a, b])  #  c=∑i∑j Aij Bij = Aij Bij

a: tensor([[0, 1, 2],
        [3, 4, 5]]) 

b: tensor([[ 6,  7,  8],
        [ 9, 10, 11]]) 



tensor(145)

#### HADAMARD PRODUCT

In [ ]:
a = torch.arange(6).reshape(2, 3)
print(f"a: {a} \n")
b = torch.arange(6,12).reshape(2, 3)
print(f"b: {b} \n")
torch.einsum('ij,ij->ij', [a, b]) # Cij = AijBij

a: tensor([[0, 1, 2],
        [3, 4, 5]]) 

b: tensor([[ 6,  7,  8],
        [ 9, 10, 11]]) 



tensor([[ 0,  7, 16],
        [27, 40, 55]])

#### OUTER PRODUCT

In [ ]:
a = torch.arange(3)
print(f"a: {a} \n")
b = torch.arange(3,7)  # -- a vector of length 4 containing [3, 4, 5, 6]
print(f"b: {b} \n")
torch.einsum('i,j->ij', [a, b])  # Cij = aibj

a: tensor([0, 1, 2]) 

b: tensor([3, 4, 5, 6]) 



tensor([[ 0,  0,  0,  0],
        [ 3,  4,  5,  6],
        [ 6,  8, 10, 12]])

#### BATCH MATRIX MULTIPLICATION

In [ ]:
a = torch.arange(30).reshape(3,2,5)
print(f"a: {a} \n")
b = torch.arange(45).reshape(3,5,3)
print(f"b: {b} \n")
torch.einsum('ijk,ikl->ijl', [a, b])  # Cijl = ∑k Aijk Bikl = Aijk Bikl

a: tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9]],

        [[10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]]]) 

b: tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11],
         [12, 13, 14]],

        [[15, 16, 17],
         [18, 19, 20],
         [21, 22, 23],
         [24, 25, 26],
         [27, 28, 29]],

        [[30, 31, 32],
         [33, 34, 35],
         [36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]]]) 



tensor([[[  90,  100,  110],
         [ 240,  275,  310]],

        [[1290, 1350, 1410],
         [1815, 1900, 1985]],

        [[3990, 4100, 4210],
         [4890, 5025, 5160]]])

#### TENSOR CONTRACTION
Batch matrix multiplication is a special case of a tensor contraction. Let's say we have two tensors, an order-n tensor A∈RI1×⋯×In and an order-m tensor B∈RJ1×⋯×Im. As an example, take n=4, m=5 and assume that I2=J3 and I3=J5. We can multiply the two tensors in these two dimensions (2 and 3 for A and 3 and 5 for B) resulting in a new tensor C∈RI1×I4×J1×J2×J4 as follows

Cpstuv=∑q∑rApqrsBtuqvr=ApqrsBtuqvr

In [ ]:
a = torch.randn(2,3,5,7)
b = torch.randn(11,13,3,17,5)
torch.einsum('pqrs,tuqvr->pstuv', [a, b]).shape

torch.Size([2, 7, 11, 13, 17])

#### BILINEAR TRANSFORMATION

As mentioned earlier, einsum can operate on more than two tensors. One example where this is used is bilinear transformation.

Dij=∑k∑lAikBjklCil=AikBjklCil

In [ ]:
a = torch.randn(2,3)
b = torch.randn(5,3,7)
c = torch.randn(2,7)
torch.einsum('ik,jkl,il->ij', [a, b, c])

tensor([[ 4.5470, -2.0217,  1.4526,  0.0379,  0.7637],
        [-0.6053,  1.2503, -5.1426,  1.4413, -3.6375]])